# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bambuddy
version: "0.1.8-1"
slug: bambuddy
description: Bambuddy is a powerful, self-hosted print archive and management system for Bambu Lab 3D printers.
url: "https://github.com/hobbypunk90/homeassistant-addon-bambuddy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
hassio_role: homeassistant
privileged:
  - NET_RAW
homeassistant_api: true
options:
  debug: false
schema:
  debug: bool
ports:
  8000/tcp: 8000
webui: http://[HOST]:[PORT:8000]
watchdog: http://[HOST]:[PORT:8000]/health